#=========================================
#           配置项目名已经端口
#=========================================
spring:
  application:
    name: eureak-server
server:
  port: 890
#=========================================
#           配置eureka的基本信息
#=========================================
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:890/eureka/
#      defaultZone: http://${eureka.instance.hostname}:891/eureka/
    fetch-registry: false
    register-with-eureka: false
  server:
#    本地调试关闭保护机制
    enable-self-preservation: true
#=========================================
#           添加安全验证
#=========================================
security:
  basic:
    enabled: true
  user:
    password: 59421
    name: silu
