server:
  port: 80
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
  application:
    name: WEB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:890/eureka/
# 自定义
app:
  host: http://127.0.0.1/
  encoding: utf-8
  