app:
  host: http://127.0.0.1/
  encoding: utf-8
  sorry: 我们的后台出问题了
  sorryDesc: 我们的后台出问题了就是那种要杀程序员祭天的问题
  sorryTitle: 杀程序员祭天了
  sorryUrl: ./
  php:
    url: http://PHP-DATA-PROVIDER
    name: PHP-DATA-PROVIDER
  nodejs:
    url: http://NODEJS-PROVIDER
    name: NODEJS-PROVIDER
  java: 
    url: http://JAVA-PROVIDER
    name: JAVA-PROVIDER